name: artamos
favicon: null
layout_spectrum: 0.6196383680216968
typography_spectrum: 0.696827377891168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#696a6e'
    - '#16918f'
    - '#292a2f'
    - '#cac9c7'
  brandStrength: 0.375
  lightness: 0.11076200543902814
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
